module.exports = {
    //flushQueue: require('./bose.music.flushQueue.js'),
    getCurrentTrack: require('./bose.music.getCurrentTrack.js'),
    getMuted: require('./bose.music.getMuted.js'),
    getPlaying: require('./bose.music.getPlaying.js'),
    //getPlaylists: require('./bose.music.getPlaylists.js'),
    //getQueue: require('./bose.music.getQueue.js'),
    getVolume: require('./bose.music.getVolume.js'),
    next: require('./bose.music.next.js'),
    pause: require('./bose.music.pause.js'),
    play: require('./bose.music.play.js'),
    playPlaylist: require('./bose.music.playPlaylist.js'),
    previous: require('./bose.music.previous.js'),
    setMuted: require('./bose.music.setMuted.js'),
    setVolume: require('./bose.music.setVolume.js'),
    stop: require('./bose.music.stop.js'),
};